{% set name = "pyod" %}
{% set version = "1.1.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/yzhao062/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 5f301b040ddb8e792714d0562588cc55f600c5584c6c6fa64e1f691942dc27e8

build:
  # From upstream "Required Dependencies Python 3.6 or higher"
  skip: True  # [py<36]
  # Dependency numpy<2.0 not available for Python 3.13
  skip: True  # [py>=313]
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  build:
    - patch  #[not win]
    - m2-patch  #[win]
  host:
    - pip
    - python
    - setuptools >=38.6.0
    - wheel
  run:
    - python
    - joblib
    - matplotlib-base
    - numpy >=1.19, <2.0
    - numba >=0.51
    - scipy >=1.5.1
    - scikit-learn >=0.22.0
    - six
  run_constrained:
    # contraining tensorflow to >=2.12,<2.16 to enable legacy keras, which is needed for following models
    # alad, anogan, auto_encoder, deep_svdd, gaal_base, mo_gaal, so_gaal, vae
    - tensorflow >=2.12,<2.16

  # Missing combo dependency
  {% set ignore_tests = "" %}
  {% set ignore_tests = ignore_tests + " --ignore=pyod/test/test_combination.py" %}
  {% set ignore_tests = ignore_tests + " --ignore=pyod/test/test_feature_bagging.py" %}

  # tensorflow.keras.optimizers missing from keras >=2.12, pinned by tensorflow >=2.12
  {% set ignore_tests = ignore_tests + " --ignore=pyod/test/test_mo_gaal.py" %}

  # segfault on osx-arm64
  {% set ignore_tests = ignore_tests + " --ignore=pyod/test/test_auto_encoder_torch.py" %}

  # Missing suod dependency
  {% set ignore_tests = ignore_tests + " --ignore=pyod/test/test_suod.py" %}

  # Missing pythresh dependency
  {% set ignore_tests = ignore_tests + " --ignore=pyod/test/test_thresholds.py" %}

test:
  source_files:
    - pyod/test
  imports:
    - pyod
    - pyod.models
    - pyod.utils
  requires:
    - pytest
    - xgboost
    - pandas
    - tensorflow >=2.12,<2.16
    - keras
    - pytorch
    - statsmodels
  commands:
    # skipping pip check because of errors with tensorflow, which is an optional dependency
    # - pip check
    - python -c "from importlib.metadata import version; assert(version('{{ name }}')=='{{ version }}')"

    - pytest -vv {{ ignore_tests }} pyod/test

about:
  home: https://github.com/yzhao062/pyod
  dev_url: https://github.com/yzhao062/pyod
  doc_url: https://pyod.readthedocs.io
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE
  summary: A Python Toolkit for Scalable Outlier Detection (Anomaly Detection)
  description: A Python Toolkit for Scalable Outlier Detection (Anomaly Detection)

extra:
  recipe-maintainers:
    - yzhao062
    - apcamargo
