{% set name = "pyod" %}
{% set version = "2.0.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/yzhao062/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: c2ce8cdcba28e6de1b505c9fa716665df79a1c8ac4ff26e124b76d4981315e73

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - pip
    - python
    - wheel
    - setuptools >=38.6.0
  run:
    - python
    - joblib
    - matplotlib-base
    - numpy >=1.19
    - numba >=0.51
    - scipy >=1.5.1
    - scikit-learn >=0.22.0

test:
  imports:
    - pyod
    - pyod.models
    - pyod.utils
  commands:
    - pip check
    - python -c "from importlib.metadata import version; assert(version('{{ name }}')=='{{ version }}')"

    # Missing suod dependency
    - rm ${SP_DIR}/pyod/test/test_suod.py  # [unix]
    - del /f /q %SP_DIR%\pyod\test\test_suod.py  # [win]

    # Missing combo dependency
    - rm ${SP_DIR}/pyod/test/test_combination.py  # [unix]
    - del /f /q %SP_DIR%\pyod\test\test_combination.py  # [win]
    - rm ${SP_DIR}/pyod/test/test_feature_bagging.py  # [unix]
    - del /f /q %SP_DIR%\pyod\test\test_feature_bagging.py  # [win]

    - pytest --pyargs pyod.test
  requires:
    - pip
    - pytest
    - xgboost
    - pandas
    - pytorch-cpu
    - statsmodels
    - tqdm

about:
  home: https://github.com/yzhao062/pyod
  dev_url: https://github.com/yzhao062/pyod
  doc_url: https://pyod.readthedocs.io
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE
  summary: A Python Toolkit for Scalable Outlier Detection (Anomaly Detection)
  description: A Python Toolkit for Scalable Outlier Detection (Anomaly Detection)

extra:
  recipe-maintainers:
    - yzhao062
    - apcamargo
