{% set name = "pyod" %}
{% set version = "0.8.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 4d16c3989667d666dac757615293f29ec20e848140fe9c779e69454e59557dbb

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
  run:
    - joblib
    - matplotlib-base
    - numba >=0.35
    - numpy >=1.13
    - python
    - scikit-learn >=0.19.1
    - scipy >=0.19.1
    - six

test:
  imports:
    - pyod
    - pyod.models
    - pyod.utils

about:
  home: https://github.com/yzhao062/pyod
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE
  summary: A Python Toolkit for Scalable Outlier Detection (Anomaly Detection)
  doc_url: https://pyod.readthedocs.io

extra:
  recipe-maintainers:
    - yzhao062
    - apcamargo
