{% set name = "pyod" %}
{% set version = "1.0.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 592f83e172710d582ce214a5457932e103f1ae62ca375fff60729063fac72f5d

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.5
  run:
    - python >=3.5
    - joblib
    - matplotlib-base
    - numba >=0.51
    - numpy >=1.19
    - scikit-learn >=0.20.0
    - scipy >=1.5.1
    - six
    - statsmodels

test:
  imports:
    - pyod
    - pyod.models
    - pyod.utils

about:
  home: https://github.com/yzhao062/pyod
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE
  summary: A Python Toolkit for Scalable Outlier Detection (Anomaly Detection)
  doc_url: https://pyod.readthedocs.io

extra:
  recipe-maintainers:
    - yzhao062
    - apcamargo
