{% set name = "pyod" %}
{% set version = "1.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: c1659f7f55eba5bafd25cb28b469084fd5394e241af7eecf655c704cae36f0c7

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.5
  run:
    - python >=3.5
    - joblib
    - matplotlib-base
    - numba >=0.51
    - numpy >=1.19
    - scikit-learn >=0.20.0
    - scipy >=1.5.1
    # until numba and scipy is hotfixed: it brings in the wrong numpy
    # - numpy <1.23.0
    
    # numba needs 1.21 or less but it isn't declared in the metadata
    - numpy <=1.21
    - six
    - statsmodels

test:
  imports:
    - pyod
    - pyod.models
    - pyod.utils

about:
  home: https://github.com/yzhao062/pyod
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE
  summary: A Python Toolkit for Scalable Outlier Detection (Anomaly Detection)
  doc_url: https://pyod.readthedocs.io

extra:
  recipe-maintainers:
    - yzhao062
    - apcamargo
